[marcela]
title = "Marcela Properties"
url = "https://www.marcelapropriedades.com/properties-for-sale/-1/-1/-1/-1/-1/720/-/0/0/0/0/0/0/-/-1"
entrySelector = "li.propsList__col"
waitUntil = "networkidle"
titleSelector = ["p:first-of-type", "p:nth-of-type(2) strong"]
linkSelector = "a[href]:first-of-type"
contentSelector = ["img", "p:first-of-type"]

[remax]
title = "Remax Aljezur"
url = "https://remax.pt/en/buy?searchQueryState={%22regionName%22:%22Aljezur%22,%22businessType%22:1,%22listingClass%22:1,%22page%22:1,%22regionID%22:%22357%22,%22regionType%22:%22Region2ID%22,%22sort%22:{%22fieldToSort%22:%22ContractDate%22,%22order%22:1},%22mapIsOpen%22:false,%22regionCoordinates%22:{%22latitude%22:37.301601324483805,%22longitude%22:-8.811593597050145},%22regionZoom%22:12,%22prn%22:%22Aljezur,%20Faro%22}"
entrySelector = "a[data-id='listing-card-link']"
waitUntil = "networkidle"
titleSelector = ["b span", "p"]
linkSelector = "a[data-id='listing-card-link']"
contentSelector = ["img", "p"]

[mimosa]
title = "Mimosa"
url = "https://www.mimosaproperties.com/conteudos/imoveis/default.aspx?pg=1&o=1&g=&e=&pp=176&dd=08&cc=03&ff=&ml=&z=&nq=&p=&a=&c=&es=&ct=00000001&or=30&idioma=pt1"
entrySelector = ".card-imovel_flex"
waitUntil = "networkidle"
titleSelector = [".preco_actual", ".card-imovel_titulo .titulo"]
linkSelector = ".card-imovel_titulo[href]"
contentSelector = [".card-imovel_img img", ".card-imovel_localidade"]

[century21]
title = "Century 21"
url = "https://www.century21global.com/en/l/homes-for-sale/portugal,faro,aljezur?sort=PRICE&order=ASC"
entrySelector = "site-property-thumbnail"
waitUntil = "networkidle"
titleSelector = [".mat-display-1", ".fw-semibold.mb-0"]
linkSelector = "a[href^='/en/p/']"
contentSelector = ["img", ".fw-semibold.mb-0"]

[provenda]
title = "Provenda"
url = "https://www.provenda.net/en/properties/"
entrySelector = ".listw"
waitUntil = "networkidle"
titleSelector = [".lpprice", ".lptitle"]
linkSelector = ".lptitle[href]"
contentSelector = [".limg img", ".lptext"]

[era]
title = "ERA Aljezur"
url = "https://www.era.pt/en/buy?ob=1&tp=1,2&lc=08-03&page=1&ord=3"
entrySelector = ".card"
waitUntil = "networkidle"
titleSelector = [".price-value", ".location"]
linkSelector = "a.card__gallery[href]"
contentSelector = [".slide[style*='background-image: url']", ".location", ".property-type", ".property-details"]

[oando]
title = "Oando"
url = "https://oando.pt/westalgarve/advanced-search/?lang=en&advanced_city%5B%5D=aljezur&bedrooms=&wcs=&price_low=No+Value&price_max=No+Value&price_label_component=&reference=&submit=Search+Properties&wpestate_regular_search_nonce=d73ae0a8d0&_wp_http_referer=%2Fwestalgarve%2Fproperties%2F%3Fsearch_location%26mscbo_city%255B0%255D%3Dcity-aljezur%26mscbo_locality%255B0%255D%3Dlocality-aljezur%26mscbo_locality%255B1%255D%3Dlocality-bordeira%26mscbo_locality%255B2%255D%3Dlocality-rogil%26location_zone%255B0%255D%3DAljezur%26location_zone%255B1%255D%3DEspartal%26location_zone%255B2%255D%3DPaisagem%2BOceano%26location_zone%255B3%255D%3DVale%2BDa%2BTelha%26location_zone%255B4%255D%3DCarrapateira%26location_zone%255B5%255D%3DRogil%26property_price_min%3D-1%26property_price_max%3D-1%26property_reference"
entrySelector = ".listing_wrapper"
waitUntil = "networkidle"
titleSelector = [".property-unit-information-wrapper h4 a", ".listing_unit_price_wrapper"]
linkSelector = ".property-unit-information-wrapper h4 a[href]"
contentSelector = [".carousel-item.active img", ".listing_details.the_grid_view", ".property_listing_details", ".property-ref"]

[swplaces]
title = "SW-Places"
url = "https://sw-places.com/properties?location=%7B%22620%22:%7B%221%22:%7B%228%22:%7B%223%22:%7B%7D%7D%7D%7D%7D"
entrySelector = ".row.property-area"
waitUntil = "load"
titleSelector = [".property-title", ".title.mt-3"]
linkSelector = ".property-title a[href]"
contentSelector = [".homes-img img", ".preview-description", ".homes-list", ".title.mt-3"]

[mikasa]
title = "Mikasa"
url = "https://www.mikasainvest.pt/en/lista-propriedades?city=720&order=0"
entrySelector = "a.propertyItemStyle3"
titleSelector = [".propertyItemStyle3__panel__title", ".propertyItemStyle3__panel__price"]
linkSelector = "a.propertyItemStyle3[href]"
contentSelector = [".propertyItemStyle3__img", ".propertyItemStyle3__panel__title", ".propertyItemStyle3__panel__price", ".propertyItemStyle3__panel__info"]
waitUntil = "networkidle"
