[marcela]
title = "Marcela Properties"
url = "https://www.marcelapropriedades.com/properties-for-sale/-1/-1/-1/-1/-1/720/-/0/0/0/0/0/0/-/-1"
entrySelector = "li.propsList__col"
waitUntil = "networkidle"
titleSelector = "meta[itemprop=name][content]"
linkSelector = "a.prop__link[href]"

[remax]
title = "Remax Aljezur"
url = "https://remax.pt/en/buy?searchQueryState={%22regionName%22:%22Aljezur%22,%22businessType%22:1,%22listingClass%22:1,%22page%22:1,%22regionID%22:%22357%22,%22regionType%22:%22Region2ID%22,%22sort%22:{%22fieldToSort%22:%22ContractDate%22,%22order%22:1},%22mapIsOpen%22:false,%22regionCoordinates%22:{%22latitude%22:37.301601324483805,%22longitude%22:-8.811593597050145},%22regionZoom%22:12,%22prn%22:%22Aljezur,%20Faro%22}"
entrySelector = ".listing-search-searchresults-component div.result > div.listing-search-searchdetails-component"
waitUntil = "networkidle"
titleSelector = "p.listing-price"
linkSelector = "a[href]"
contentSelector = "div.listing-card"

[mimosa]
title = "Mimosa"
url = "https://www.mimosaproperties.com/imoveis/?pg=1&o=1&g=&t=&e=&dd=08&cc=03&ff=&ml=&z=&nq=&p=&a=&c=&ct=0000000000001&or=30&idioma=en"
entrySelector = "#ContentPlaceHolder1_moduloimoveislistagem_listagem_imoveis_holder > div.comp-item-imovel"
waitUntil = "networkidle"
titleSelector = "a.img-imovel[title]"
linkSelector = "a.img-imovel[href]"
contentSelector = "a.img-imovel"

[century21]
title = "Century 21"
url = "https://www.century21global.com/for-sale-residential/Portugal/Faro-%28Algarve%29/Aljezur-%28Algarve%29"
entrySelector = "div.search-result"
waitUntil = "networkidle"
titleSelector = "div.price-native > span"
linkSelector = "a.search-result-info[href]"

[luxview]
title = "Luxview"
url = "https://en.luxview.pt/properties-list/1/0/373230/0/0/0/0/-/1"
entrySelector = "li.grid-item"
waitUntil = "networkidle"
titleSelector = "span.prop-price"
linkSelector = "a.prop[href]"

[provenda]
title = "Provenda"
url = "https://www.provenda.net/en/properties/"
entrySelector = ".listw"
waitUntil = "networkidle"
titleSelector = ".lptitle"
linkSelector = "a.lptitle[href]"

[era]
title = "ERA Aljezur"
url = "https://www.era.pt/en/buy?ob=1&tp=1,2&lc=08-03&page=1&ord=3"
entrySelector = ".card"
waitUntil = "load"
titleSelector = ".sr-only"
linkSelector = "a.card__gallery[href]"

[chestertons]
title = "Chestertons"
url = "https://www.chestertons-portugal.com/properties-list/1/-1/3732307c416c6a657a7572/-1/-1/-1/-1/-1/-1/-1/-1/-1/-1/-1/-1/12/-1"
entrySelector = ".list__item"
waitUntil = "networkidle"
titleSelector = ".prop__title"
linkSelector = "a.prop[href]"

[century21-pt]
title = "Century 21 Portugal"
url = "https://www.century21.pt/en/for-sale/property-type/aljezur-algarve/?q=portugal+faro-algarve+aljezur-algarve&ord=date-desc&r=&page=1&numberOfElements=12&v=c"
entrySelector = ".property-list-item"
waitUntil = "networkidle"
titleSelector = ".title-link"
linkSelector = "a.card-agent-photo[href]"